FROM elasticsearch:7.9.3

LABEL maintainer="lee1031 <ligangmingx@gmail.com>"

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.9.3/elasticsearch-analysis-ik-7.9.3.zip