FROM elasticsearch:7.10.1

LABEL maintainer="lee1031 <ligangmingx@gmail.com>"

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.10.0/elasticsearch-analysis-ik-7.10.0.zip